[options]
addons_path = /mnt/extra-addons

# Database
db_host = db
db_name = produccion
db_port = 5432
db_user = odoo
db_password = odoo
dbfilter = ^produccion$
list_db = False

# HTTP
http_port = 8069
admin_passwd = admin
proxy_mode = True

# Locale
load_language = es_EC
country_code = EC

# Workers — tuned for t3.medium (4GB RAM)
workers = 2
limit_memory_soft = 671088640
limit_memory_hard = 805306368
limit_time_cpu = 600
limit_time_real = 1200

# Startup
init = l10n_ec
without_demo = all

# Logging
log_level = info
